// Generated by tools/generate-capabilities.mjs — do not edit by hand.
//
// Source: the `Caps` column of https://commandcode.ai/docs/plans/go, which states each model's
// capabilities verbatim in an aria-label, e.g.
// `Capabilities: Text input, Vision, Reasoning`.
//
// This is the vendor's own statement, so it wins over inference. An earlier build
// measured capabilities by probing models through an OpenAI-compatible proxy,
// which does not forward image parts — that marked 10 vision-capable models as
// text-only (every Kimi among them) and disagreed on reasoning for 14 more.
//
// The runtime reads the same page (see `src/plan-catalog.ts`), so this file only
// covers models the picker would otherwise have to guess about. Models absent
// here fall back to CONSERVATIVE_CAPABILITIES.
//
// Generated from the go plan on 2026-10-04.

/**
 * Default capabilities for a model with no vendor-declared entry.
 *
 * Vision is off on purpose: an unknown model that silently drops images is a
 * smaller problem than a text-only model being handed image bytes. Tools stay on
 * because every callable model in the measured set supported them.
 */
export const CONSERVATIVE_CAPABILITIES = {
	vision: false,
	thinking: true,
} as const;

/**
 * Vendor-declared capabilities, keyed by catalog model id.
 *
 * `vision` comes from the plan page listing Vision in the model's Caps column;
 * `thinking` likewise for Reasoning. Context windows are deliberately absent:
 * they come from the live catalog at runtime, which is always newer than this file.
 */
export const MEASURED_CAPABILITIES: Readonly<Record<string, MeasuredCapability>> = {
	'deepseek/deepseek-v4.1-flash-fast': { vision: true, thinking: true },
	'inclusionai/ling-3.1-flash:free': { vision: false, thinking: true },
	'gpt-6-luna': { vision: true, thinking: true },
	'stealth/space-bunny-alpha': { vision: true, thinking: true },
	'xiaomi/mimo-v2.6-flash': { vision: true, thinking: false },
	'xiaomi/mimo-v2.6-pro': { vision: true, thinking: false },
	'stepfun/Step-5-Preview': { vision: true, thinking: true },
	'z-ai/glm-5.3-flashx': { vision: true, thinking: true },
	'Qwen/Qwen3.8-Omni-Flash': { vision: true, thinking: true },
	'deepseek/deepseek-v4.1-flash': { vision: true, thinking: true },
	'inclusionai/ling-3.0-flash-sante:free': { vision: false, thinking: true },
	'meta/muse-spark-1.3-contributor': { vision: true, thinking: true },
	'Qwen/Qwen3.8-Max-0902': { vision: true, thinking: true },
	'tencent/hy4-preview': { vision: false, thinking: true },
	'z-ai/glm-5.3-flash': { vision: true, thinking: true },
	'meituan/LongCat-2.0': { vision: false, thinking: true },
	'Qwen/Qwen3.8-Flash': { vision: true, thinking: true },
	'deepseek/deepseek-v4-flash-fast': { vision: false, thinking: true },
	'deepseek/deepseek-v4-flash-vision-exp': { vision: true, thinking: true },
	'zai-org/GLM-5.3': { vision: false, thinking: true },
	'Qwen/Qwen3.8-27B': { vision: true, thinking: true },
	'deepseek/deepseek-v4-pro': { vision: false, thinking: true },
	'meta/muse-spark-1.2-contributor': { vision: true, thinking: true },
	'Qwen/Qwen3.8-Max': { vision: true, thinking: true },
	'deepseek/deepseek-v4-flash': { vision: false, thinking: true },
	'thinkingmachines/inkling-small': { vision: true, thinking: true },
	'Qwen/Qwen3.7-Flash': { vision: true, thinking: true },
	'poolside/laguna-s-2.1-free': { vision: false, thinking: true },
	'thinkingmachines/inkling': { vision: true, thinking: true },
	'moonshotai/Kimi-K3': { vision: true, thinking: true },
	'gpt-5.6-luna': { vision: true, thinking: true },
	'xai/grok-4.5': { vision: true, thinking: true },
	'tencent/hy3-paid': { vision: false, thinking: true },
	'zai-org/GLM-5.2-Fast': { vision: false, thinking: false },
	'zai-org/GLM-5.2': { vision: false, thinking: true },
	'moonshotai/Kimi-K2.7-Code-Highspeed': { vision: true, thinking: true },
	'moonshotai/Kimi-K2.7-Code': { vision: true, thinking: true },
	'nvidia/nemotron-3-ultra-550b-a55b': { vision: false, thinking: true },
	'MiniMaxAI/MiniMax-M3': { vision: true, thinking: true },
	'Qwen/Qwen3.7-Plus': { vision: true, thinking: true },
	'stepfun/Step-3.7-Flash': { vision: true, thinking: true },
	'xiaomi/mimo-v2.5': { vision: true, thinking: false },
	'xiaomi/mimo-v2.5-pro': { vision: false, thinking: false },
	'Qwen/Qwen3.7-Max': { vision: false, thinking: true },
	'stepfun/Step-3.5-Flash': { vision: false, thinking: true },
	'zai-org/GLM-5.1': { vision: false, thinking: false },
	'MiniMaxAI/MiniMax-M2.7': { vision: false, thinking: false },
	'Qwen/Qwen3.6-Max-Preview': { vision: false, thinking: true },
	'Qwen/Qwen3.6-Plus': { vision: true, thinking: true },
	'moonshotai/Kimi-K2.6': { vision: true, thinking: false },
	'zai-org/GLM-5': { vision: false, thinking: false },
	'moonshotai/Kimi-K2.5': { vision: true, thinking: false },
	'MiniMaxAI/MiniMax-M2.5': { vision: false, thinking: false },
};

export interface MeasuredCapability {
	/** Vendor-declared vision support. */
	readonly vision: boolean;
	/** Vendor-declared reasoning support. */
	readonly thinking: boolean;
}

/**
 * Look up vendor-declared capabilities for a catalog model id.
 */
export function measuredCapabilities(modelId: string): MeasuredCapability | undefined {
	return MEASURED_CAPABILITIES[modelId];
}
